apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: bookinfo-rule
  namespace: bookinfo-project
  generation: 1
  labels:
    purpose: icam-demo
spec:
  clusterLabels:
    matchLabels:
      environment: Dev
  clusterReplicas: 1
